site_name: 'Technical Docs'
theme:
    name: readthedocs
    color_mode: auto
    user_color_mode_toggle: true
    highlightjs: true
    hljs_languages:
        - yaml
        - java
nav:
  - Caching and Filtering: caching-and-filtering.md
  - eTags in APIs: eTags.md
  - HATEOAS in APIs: hateoas.md
  - Idempotency in APIs: idempotency.md
  - Rate Limit and Throttling: rate-limiting-and-throttling.md
  - Temporal and Spring Boot: temporal-with-springboot.md

